
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD66A0931WdPK3SUIQl-WUYhPooTY4JW8',
    iosBundleId: 'com.giolab.ragaca',
    appId: '1:85463742507:ios:698abdb63c68145db4526e',
    storageBucket: 'ragaca-6d90f.appspot.com',
    messagingSenderId: '85463742507',
    iosClientId: 'undefined',
    projectId: 'ragaca-6d90f'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Lo6FTFFPP4XdH6_us72NEzZ9K8ueXmE',
    appId: '1:85463742507:android:1298811581da1d53b4526e',
    messagingSenderId: '85463742507',
    projectId: 'ragaca-6d90f',
    storageBucket: 'ragaca-6d90f.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VkRWbHdRZal62FwbwTi2tcNzXZpVMiQ',
    authDomain: 'ragaca-6d90f.firebaseapp.com',
    projectId: 'ragaca-6d90f',
    storageBucket: 'ragaca-6d90f.appspot.com',
    messagingSenderId: '85463742507',
    appId: '1:85463742507:web:ce67b23b85baa596b4526e',
    measurementId: 'G-3KY4M3LS44'
  );
}
